# Generated by Django 6.0.7 on 2026-07-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="post",
            fields=[
                ("title_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("titel", models.CharField(max_length=100)),
                ("contant", models.TextField(max_length=200)),
                ("date", models.DateField()),
            ],
        ),
    ]
